name: Deploy to Snowflake

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "Environment"
        required: true

jobs:
  deploy:
    name: Deploy to Snowflake
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x

      - name: Install dependencies
        run: |
          pip install schemachange

      - name: Deploy to ${{ inputs.environment }}
        run: |
          SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}
          SNOWFLAKE_USERNAME=${{ secrets.SNOWFLAKE_USERNAME_DEV }}
          SNOWFLAKE_ROLE=${{ secrets.SNOWFLAKE_ROLE_DEV }}
          SNOWFLAKE_WAREHOUSE=${{ secrets.SNOWFLAKE_WAREHOUSE_DEV }}
          SNOWFLAKE_DATABASE=${{ secrets.SNOWFLAKE_DATABASE_DEV }}
          SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD_DEV }}
          if [[ "${{ inputs.environment }}" == "qut" ]]; then
            SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT_QUT }}
            SNOWFLAKE_USERNAME=${{ secrets.SNOWFLAKE_USERNAME_QUT }}
            SNOWFLAKE_ROLE=${{ secrets.SNOWFLAKE_ROLE_QUT }}
            SNOWFLAKE_WAREHOUSE=${{ secrets.SNOWFLAKE_WAREHOUSE_QUT }}
            SNOWFLAKE_DATABASE=${{ secrets.SNOWFLAKE_DATABASE_QUT }}
            SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD_QUT }}
          elif [[ "${{ inputs.environment }}" == "prd" ]]; then
            SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT_PRD }}
            SNOWFLAKE_USERNAME=${{ secrets.SNOWFLAKE_USERNAME_PRD }}
            SNOWFLAKE_ROLE=${{ secrets.SNOWFLAKE_ROLE_PRD }}
            SNOWFLAKE_WAREHOUSE=${{ secrets.SNOWFLAKE_WAREHOUSE_PRD }}
            SNOWFLAKE_DATABASE=${{ secrets.SNOWFLAKE_DATABASE_PRD }}
            SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD_PRD }}
          fi
          schemachange -f $GITHUB_WORKSPACE -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USERNAME -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -c $SNOWFLAKE_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table

      - name: Notify success
        if: success()
        run: echo "${{ inputs.environment }} deployment succeeded!"

      - name: Notify failure
        if: failure()
        run: echo "${{ inputs.environment }} deployment failed!"
