
# This would be a part of a job in your main workflow file

steps:
  # Use Python 3.x
  - name: Use Python 3.x
    uses: actions/setup-python@v2
    with:
      python-version: '3.x'

  # Install schemachange
  - name: Install schemachange
    run: pip install schemachange

  # Run Deployment
  - name: Run Deployment
    run: schemachange --config-folder ${{ github.workspace }}/cicd/schemachange_config/${{ env.env }} ${{ env.dry_run }}
    env:
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASS }}
      dry_run: ${{ github.event.inputs.dry_run }}
    working-directory: ${{ github.workspace }}
