name: Snowflake All ENV

on:
  push:
    branches:
      - devv
  workflow_dispatch:

jobs:
  dev:
    name: Deploy Dev
    uses: ./.github/workflows/deploy_dev.yml

  qut:
    name: Deploy Qut
    needs: dev
    if: github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/deploy_qut.yml

  prd:
    name: Deploy Prd
    needs: qut
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/deploy_prd.yml
