name: Snowflake_CICD_NEW

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy_dev:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev

  deploy_qut:
    needs: deploy_dev
    if: ${{ github.ref == 'refs/heads/dev' }}
    uses: ./.github/workflows/deploy.yml
    with:
      environment: qut

  deploy_prd:
    needs: deploy_qut
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prd
