name: Snowflake_CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  deploy_tst:
    runs-on: ubuntu-latest
    environment: tst
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install schemachange

      - name: Deploy to TST
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASS }}
        run: |
          schemachange --config-folder ${{ github.workspace }}/cicd

  # deploy_prd:
  #   needs: deploy_tst
  #   runs-on: ubuntu-latest
  #   environment: prd
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Set up Python 3.8
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.8' 

  #     - name: Install dependencies
  #       run: pip install schemachange

  #     - name: Deploy to PRD
  #       if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
  #       env:
  #         SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASS }}
  #       run: |
  #         schemachange --config-file ${{ github.workspace }}/cicd/schemachange-config-prod.yml
