name: Snowflake_CI_CD

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy_tst:
    runs-on: ubuntu-latest
    env:
      env: tst
    steps:
      # Checkout the repository
      - name: Retrieve repository
        uses: actions/checkout@v2
      
      # Run dry run
      - name: Dry Run TST
        uses: ./.github/workflows/deploy-template.yaml
        with:
          snowflake_password: ${{ secrets.SNOWFLAKE_PASS }}
          dry_run: '--dry-run'
      
      # Wait for manual validation of dry run
      - name: Dry Run Validation TST
        uses: ./.github/workflows/wait-template.yaml
      
      # Run deployment
      - name: Deploy TST
        uses: ./.github/workflows/deploy-template.yaml
        with:
          snowflake_password: ${{ secrets.SNOWFLAKE_PASS }}
          dry_run: ''

  deploy_prd:
    needs: deploy_tst
    runs-on: ubuntu-latest
    env:
      env: prd
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      
      # Run dry run
      - name: Dry Run PRD
        uses: ./.github/workflows/deploy-template.yaml
        with:
          snowflake_password: ${{ secrets.SNOWFLAKE_PASS }}
          dry_run: '--dry-run'
      
      # Wait for manual validation of dry run
      - name: Dry Run Validation PRD
        uses: ./.github/workflows/deploy-template.yaml
      
      # Run deployment
      - name: Deploy PRD
        uses: ./.github/workflows/wait-template.yaml
        with:
          snowflake_password: ${{ secrets.SNOWFLAKE_PASS }}
          dry_run: ''
