name: wf_schemachange

on:
  push:
    branches:
      - dev
  workflow_dispatch:   # Allow manual triggering of the workflow

jobs:
  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Retrieve repository
        uses: actions/checkout@v3
      
      - name: Use Python 3.8.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x

      - name: Deploy DEV
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME_DEV }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_DEV }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE_DEV }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_DEV }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_DEV }}
        run: |
          pip install schemachange
          schemachange -f $GITHUB_WORKSPACE -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USERNAME -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -c $SNOWFLAKE_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
      
      - name: Update QUT branch
        if: github.ref == 'refs/heads/dev'
        run: |
          git fetch --all
          git checkout qut
          git merge dev
          git push origin qut

  deploy_qut:
    if: github.ref == 'refs/heads/qut'
    runs-on: ubuntu-latest
    environment: qut
    steps:
      - name: Retrieve repository
        uses: actions/checkout@v3
      
      - name: Use Python 3.8.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x

      - name: Deploy QUT
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_QUT }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME_QUT }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_QUT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE_QUT }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_QUT }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_QUT }}
        run: |
          pip install schemachange
          schemachange -f $GITHUB_WORKSPACE -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USERNAME -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -c $SNOWFLAKE_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table

  # deploy_prd:
  #   runs-on: ubuntu-latest
  #   environment: prd
  #   steps:
  #     - name: Retrieve repository
  #       uses: actions/checkout@v3
      
  #     - name: Use Python 3.8.x
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.8.x

  #     - name: Deploy PRD
  #       env:
  #         SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_PRD }}
  #         SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME_PRD }}
  #         SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_PRD }}
  #         SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE_PRD }}
  #         SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_PRD }}
  #         SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_PRD }}
  #       run: |
  #         pip install schemachange
  #         schemachange -f $GITHUB_WORKSPACE -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USERNAME -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -c $SNOWFLAKE_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table

  #     - name: Update PRD branch
  #       run: |
  #         git config --global user.name 'github-actions'
  #         git config --global user.email 'github-actions@github.com'
  #         git checkout prd
  #         git merge qut
  #         git push origin prd
